[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
  'mkdir -p data cache public/assets/icons',
  'php scripts/install.php',
  'php scripts/setup_users.php'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'